# R/locales.R
#
# Locale lookup helpers.
#
# The source of truth is .spaghetti_env$FUNCTIONS — a data frame with columns:
#   fn          : English function name (uppercase)
#   description : English description text
#   de, fr, es, … : localised names (NA where not translated)
#
# This data frame is populated by .onLoad() from data/excel_functions.rds,
# which is generated by data-raw/parse_locales.R from the Microsoft TBX files.
#
# .locale_to_english() and .english_to_locale() derive their lookups from that
# frame so no separate LOCALES/LOCALES_REV lists need to be maintained.


#' Translate a function name from a locale to English.
#'
#' @param fn_name Function name string (any case).
#' @param locale  Two-letter locale code or NULL (returns fn unchanged).
#' @return English function name, or fn unchanged if no mapping found.
#' @keywords internal
.locale_to_english <- function(fn_name, locale) {
  if (is.null(locale)) return(fn_name)

  # Ensure the data frame exists
  df <- .spaghetti_env$FUNCTIONS
  if (is.null(df)) return(fn_name)

  loc_col <- tolower(substring(locale, 1, 2))

  if (!(loc_col %in% colnames(df))) return(fn_name)

  # Find the English name where the locale column matches the input
  # We use toupper for a case-insensitive match
  match_idx <- which(toupper(df[[loc_col]]) == toupper(fn_name))

  if (length(match_idx) > 0) {
    return(df$fn[match_idx[1]])
  }

  fn_name
}


#' Translate a function name from English to a locale.
#'
#' @param fn_en  English function name (any case).
#' @param locale Two-letter locale code or NULL (returns fn unchanged).
#' @return Localised name, or fn unchanged if no mapping found.
#' @keywords internal
.english_to_locale <- function(fn_en, locale) {
  if (is.null(locale)) return(fn_en)

  df <- .spaghetti_env$FUNCTIONS
  if (is.null(df)) return(fn_en)

  loc_col <- tolower(substring(locale, 1, 2))
  if (!(loc_col %in% colnames(df))) return(fn_en)

  # Find the localized name based on the English 'fn' column
  match_idx <- which(toupper(df$fn) == toupper(fn_en))

  if (length(match_idx) > 0) {
    loc_val <- df[[loc_col]][match_idx[1]]
    # If the translation is NA, fall back to English
    if (!is.na(loc_val)) return(loc_val)
  }

  fn_en
}


#' List supported locale codes.
#'
#' Returns the locale columns present in the FUNCTIONS data frame, i.e. the
#' locales for which at least partial translation data was loaded.
#'
#' @return Character vector of locale codes (e.g. `c("de", "fr", "es", …)`).
#' @export
#' @examples
#' supported_locales()
supported_locales <- function() {
  df <- .spaghetti_env$FUNCTIONS
  if (is.null(df)) return(character(0))
  setdiff(names(df), c("fn", "description", "term_id"))
}


#' Look up the English description for an Excel function.
#'
#' @param fn Character vector of function names (English, any case).
#' @return Character vector of descriptions (NA where not found).
#' @export
#' @examples
#' function_description(c("SUM", "XLOOKUP", "LAMBDA"))
function_description <- function(fn) {
  df <- .spaghetti_env$FUNCTIONS
  if (is.null(df)) return(rep(NA_character_, length(fn)))
  idx <- match(toupper(fn), df$fn)
  df$description[idx]
}


#' Return the full function data frame.
#'
#' One row per Excel function, columns: fn, description, and one column per
#' supported locale containing the localised function name (NA if not
#' translated).
#'
#' @return data.frame
#' @export
#' @examples
#' head(function_table())
function_table <- function() {
  df <- .spaghetti_env$FUNCTIONS
  if (is.null(df)) {
    warning("Function table not loaded. Run data-raw/parse_locales.R first.")
    return(data.frame())
  }
  df[, setdiff(names(df), "term_id"), drop = FALSE]
}
