# R/registry.R
#
# Source of truth: [MS-XLSX] §2.2.2 ABNF grammar, "function-list" and
# "future-function-list" productions.
# https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xlsx
#
# Three tiers:
#   LEGACY  -> no prefix   (function-list in the spec)
#   XLFN    -> _xlfn.      (future-function-list, plain _xlfn.)
#   XLWS    -> _xlfn._xlws. (FILTER, SORT — worksheet-scope dynamic arrays)
#
# ANCHORARRAY / SINGLE are synthetic wrappers generated by the translator,
# not real user-facing functions, but need the xlws tier so they get the
# right prefix when round-tripping.
#
# LAMBDA parameters get _xlpm. — handled by the parser, not here.

# ---------------------------------------------------------------------------
# LEGACY — verbatim from [MS-XLSX] function-list production
# Macro/XLM-only names (ABSREF, ADD.BAR, ACTIVE.CELL, etc.) are included
# because they appear in the spec and we must not prefix them.
# ---------------------------------------------------------------------------
#' @family internal
LEGACY <- c(
  "ABS","ABSREF","ACCRINT","ACCRINTM","ACOS","ACOSH","ACTIVE.CELL",
  "ADD.BAR","ADD.COMMAND","ADD.MENU","ADD.TOOLBAR","ADDRESS","AMORDEGRC",
  "AMORLINC","AND","APP.TITLE","AREAS","ARGUMENT","ASC","ASIN","ASINH",
  "ATAN","ATAN2","ATANH","AVEDEV","AVERAGE","AVERAGEA","AVERAGEIF","AVERAGEIFS",
  "BAHTTEXT","BESSELI","BESSELJ","BESSELK","BESSELY","BETADIST","BETAINV",
  "BIN2DEC","BIN2HEX","BIN2OCT","BINOMDIST","BREAK",
  "CALL","CALLER","CANCEL.KEY","CEILING","CELL","CHAR","CHECK.COMMAND",
  "CHIDIST","CHIINV","CHITEST","CHOOSE","CLEAN","CODE","COLUMN","COLUMNS",
  "COMBIN","COMPLEX","CONCAT","CONCATENATE","CONFIDENCE","CONVERT","CORREL",
  "COS","COSH","COUNT","COUNTA","COUNTBLANK","COUNTIF","COUNTIFS",
  "COUPDAYBS","COUPDAYS","COUPDAYSNC","COUPNCD","COUPNUM","COUPPCD","COVAR",
  "CREATE.OBJECT","CRITBINOM",
  "CUBEKPIMEMBER","CUBEMEMBER","CUBEMEMBERPROPERTY","CUBERANKEDMEMBER",
  "CUBESET","CUBESETCOUNT","CUBEVALUE","CUMIPMT","CUMPRINC",
  "CUSTOM.REPEAT","CUSTOM.UNDO",
  "DATE","DATEDIF","DATESTRING","DATEVALUE","DAVERAGE","DAY","DAYS360",
  "DB","DBCS","DCOUNT","DCOUNTA","DDB","DEC2BIN","DEC2HEX","DEC2OCT",
  "DEGREES","DELETE.BAR","DELETE.COMMAND","DELETE.MENU","DELETE.TOOLBAR",
  "DELTA","DEREF","DEVSQ","DGET","DIALOG.BOX","DIRECTORY","DISC",
  "DMAX","DMIN","DOCUMENTS","DOLLAR","DOLLARDE","DOLLARFR",
  "DPRODUCT","DSTDEV","DSTDEVP","DSUM","DURATION","DVAR","DVARP",
  "ECHO","EDATE","EFFECT","ELSE","ELSE.IF","ENABLE.COMMAND","ENABLE.TOOL",
  "END.IF","EOMONTH","ERF","ERFC","ERROR","ERROR.TYPE","EVALUATE",
  "EVEN","EXACT","EXEC","EXECUTE","EXP","EXPONDIST",
  "FACT","FACTDOUBLE","FALSE","FCLOSE","FDIST","FILES","FIND","FINDB",
  "FINV","FISHER","FISHERINV","FIXED","FLOOR","FOPEN","FOR","FOR.CELL",
  "FORECAST","FORMULA.CONVERT","FPOS","FREAD","FREADLN","FREQUENCY",
  "FSIZE","FTEST","FV","FVSCHEDULE","FWRITE","FWRITELN",
  "GAMMADIST","GAMMAINV","GAMMALN","GCD","GEOMEAN","GESTEP",
  "GET.BAR","GET.CELL","GET.CHART.ITEM","GET.DEF","GET.DOCUMENT",
  "GET.FIELD","GET.FORMULA","GET.ITEM","GET.LINK.INFO","GET.MOVIE",
  "GET.NAME","GET.NOTE","GET.OBJECT","GET.TOOL","GET.TOOLBAR","GET.VIEW",
  "GET.WINDOW","GET.WORKBOOK","GET.WORKSPACE","GETPIVOTDATA","GOTO","GROUP",
  "GROWTH",
  "HALT","HARMEAN","HELP","HEX2BIN","HEX2DEC","HEX2OCT","HLOOKUP","HOUR",
  "HYPERLINK","HYPGEOMDIST",
  "IF","IFS","IFERROR","IMABS","IMAGINARY","IMARGUMENT","IMCONJUGATE",
  "IMCOS","IMDIV","IMEXP","IMLN","IMLOG10","IMLOG2","IMPOWER","IMPRODUCT",
  "IMREAL","IMSIN","IMSQRT","IMSUB","IMSUM","INDEX","INDIRECT","INFO",
  "INITIATE","INPUT","INT","INTERCEPT","INTRATE","IPMT","IRR",
  "ISBLANK","ISERR","ISERROR","ISEVEN","ISLOGICAL","ISNA","ISNONTEXT",
  "ISNUMBER","ISODD","ISPMT","ISREF","ISTEXT","ISTHAIDIGIT",
  "KURT","LARGE","LAST.ERROR","LCM","LEFT","LEFTB","LEN","LENB","LINEST",
  "LINKS","LN","LOG","LOG10","LOGEST","LOGINV","LOGNORMDIST","LOOKUP","LOWER",
  "MATCH","MAX","MAXA","MAXIFS","MDETERM","MDURATION","MEDIAN","MID","MIDB",
  "MIN","MINA","MINIFS","MINUTE","MINVERSE","MIRR","MMULT","MOD","MODE",
  "MONTH","MOVIE.COMMAND","MROUND","MULTINOMIAL",
  "N","NA","NAMES","NEGBINOMDIST","NETWORKDAYS","NEXT","NOMINAL",
  "NORMDIST","NORMINV","NORMSDIST","NORMSINV","NOT","NOTE","NOW","NPER","NPV",
  "NUMBERSTRING",
  "OCT2BIN","OCT2DEC","OCT2HEX","ODD","ODDFPRICE","ODDFYIELD","ODDLPRICE",
  "ODDLYIELD","OFFSET","OPEN.DIALOG","OPTIONS.LISTS.GET","OR",
  "PAUSE","PEARSON","PERCENTILE","PERCENTRANK","PERMUT","PHONETIC","PI",
  "PMT","POISSON","POKE","POWER","PPMT","PRESS.TOOL","PRICE","PRICEDISC",
  "PRICEMAT","PROB","PRODUCT","PROPER","PV",
  "QUARTILE","QUOTIENT",
  "RADIANS","RAND","RANDBETWEEN","RANK","RATE","RECEIVED","REFTEXT",
  "REGISTER","REGISTER.ID","RELREF","RENAME.COMMAND","REPLACE","REPLACEB",
  "REPT","REQUEST","RESET.TOOLBAR","RESTART","RESULT","RESUME","RETURN",
  "RIGHT","RIGHTB","ROMAN","ROUND","ROUNDBAHTDOWN","ROUNDBAHTUP",
  "ROUNDDOWN","ROUNDUP","ROW","ROWS","RSQ","RTD",
  "SAVE.DIALOG","SAVE.TOOLBAR","SCENARIO.GET","SEARCH","SEARCHB","SECOND",
  "SELECTION","SERIES","SERIESSUM","SET.NAME","SET.VALUE","SHOW.BAR",
  "SIGN","SIN","SINH","SKEW","SLN","SLOPE","SMALL","SPELLING.CHECK",
  "SPREADBASE.DATA.FIELD","SQRT","SQRTPI","STANDARDIZE",
  "STDEV","STDEVA","STDEVP","STDEVPA","STEP","STEYX","SUBSTITUTE","SUBTOTAL",
  "SUM","SUMIF","SUMIFS","SUMPRODUCT","SUMSQ","SUMX2MY2","SUMX2PY2","SUMXMY2",
  "SWITCH","SYD",
  "T","TAN","TANH","TBILLEQ","TBILLPRICE","TBILLYIELD","TDIST","TERMINATE",
  "TEXT","TEXT.BOX","TEXTJOIN","TEXTREF",
  "THAIDAYOFWEEK","THAIDIGIT","THAIMONTHOFYEAR","THAINUMSOUND",
  "THAINUMSTRING","THAISTRINGLENGTH","THAIYEAR",
  "TIME","TIMEVALUE","TINV","TODAY","TRANSPOSE","TREND","TRIM","TRIMMEAN",
  "TRUE","TRUNC","TTEST","TYPE",
  "UNREGISTER","UPPER","USDOLLAR",
  "VALUE","VAR","VARA","VARP","VARPA","VDB","VIEW.GET","VLOOKUP","VOLATILE",
  "WEEKDAY","WEEKNUM","WEIBULL","WHILE","WINDOW.TITLE","WINDOWS","WORKDAY",
  "XIRR","XNPV","YEAR","YEARFRAC","YIELD","YIELDDISC","YIELDMAT","ZTEST"
)

.spaghetti_env$LEGACY <- LEGACY

# ---------------------------------------------------------------------------
# XLWS — _xlfn._xlws. prefix
# FILTER and SORT are dynamic-array worksheet-scope functions.
# ANCHORARRAY and SINGLE are synthetic wrappers used by the translator.
# ---------------------------------------------------------------------------
#' @family internal
XLWS <- c(
  "FILTER","SORT","ANCHORARRAY","SINGLE"
)

.spaghetti_env$XLWS <- XLWS

# ---------------------------------------------------------------------------
# XLFN — verbatim from [MS-XLSX] future-function-list production
# Plus extra-spec additions (365 wave functions) at the end.
# ECMA.CEILING, ISO.CEILING, NETWORKDAYS.INTL, WORKDAY.INTL and the
# FORECAST.* group appear outside the _xlfn.() alternation in the spec
# but are still future functions — listed here without the xlws sub-namespace.
# ---------------------------------------------------------------------------
#' @family internal
XLFN <- c(
  # -- Verbatim from MS-XLSX future-function-list --
  "AGGREGATE","ACOT","ACOTH","ARABIC","BASE",
  "BETA.DIST","BETA.INV","BINOM.DIST","BINOM.DIST.RANGE","BINOM.INV",
  "BITAND","BITLSHIFT","BITOR","BITRSHIFT","BITXOR",
  "BYCOL","BYROW",
  "CEILING.MATH","CEILING.PRECISE",
  "CHISQ.DIST","CHISQ.DIST.RT","CHISQ.INV","CHISQ.INV.RT","CHISQ.TEST",
  "CHOOSECOLS","CHOOSEROWS","COMBINA",
  "CONFIDENCE.NORM","CONFIDENCE.T",
  "COT","COTH","COVARIANCE.P","COVARIANCE.S","CSC","CSCH",
  "DAYS","DECIMAL","DROP",
  "ERF.PRECISE","ERFC.PRECISE","EXPAND","EXPON.DIST",
  "F.DIST","F.DIST.RT","F.INV","F.INV.RT","F.TEST",
  "FIELDVALUE","FILTERXML","FLOOR.MATH","FLOOR.PRECISE","FORMULATEXT",
  "GAMMA","GAMMA.DIST","GAMMA.INV","GAMMALN.PRECISE","GAUSS",
  "HSTACK","HYPGEOM.DIST",
  "IFNA","IMCOSH","IMCOT","IMCSC","IMCSCH","IMSEC","IMSECH","IMSINH","IMTAN",
  "ISFORMULA","ISOMITTED","ISOWEEKNUM",
  "LAMBDA","LET","LOGNORM.DIST","LOGNORM.INV",
  "MAKEARRAY","MAP","MODE.MULT","MODE.SNGL","MUNIT",
  "NEGBINOM.DIST","NORM.DIST","NORM.INV","NORM.S.DIST","NORM.S.INV",
  "NUMBERVALUE",
  "PDURATION","PERCENTILE.EXC","PERCENTILE.INC",
  "PERCENTRANK.EXC","PERCENTRANK.INC","PERMUTATIONA","PHI",
  "POISSON.DIST","PQSOURCE","PYTHON_STR","PYTHON_TYPE","PYTHON_TYPENAME",
  "QUARTILE.EXC","QUARTILE.INC","QUERYSTRING",
  "RANDARRAY","RANK.AVG","RANK.EQ","REDUCE","RRI",
  "SCAN","SEC","SECH","SEQUENCE","SHEET","SHEETS","SKEW.P","SORTBY",
  "STDEV.P","STDEV.S",
  "T.DIST","T.DIST.2T","T.DIST.RT","T.INV","T.INV.2T","T.TEST",
  "TAKE","TEXTAFTER","TEXTBEFORE","TEXTSPLIT","TOCOL","TOROW",
  "UNICHAR","UNICODE","UNIQUE",
  "VAR.P","VAR.S","VSTACK",
  "WEBSERVICE","WEIBULL.DIST","WRAPCOLS","WRAPROWS",
  "XLOOKUP","XOR","Z.TEST",
  # -- Outside the _xlfn() alternation in spec but still future functions --
  "ECMA.CEILING","ISO.CEILING","NETWORKDAYS.INTL","WORKDAY.INTL",
  "FORECAST.ETS","FORECAST.ETS.CONFINT","FORECAST.ETS.SEASONALITY",
  "FORECAST.LINEAR","FORECAST.ETS.STAT",
  # -- Post-spec 365 additions --
  "XMATCH","IMAGE","ARRAYTOTEXT","VALUETOTEXT","TEXTJOIN"
)

.spaghetti_env$XLFN <- XLFN

# ---------------------------------------------------------------------------
# Lookup helpers
# ---------------------------------------------------------------------------

#' Determine the OOXML namespace tier for a function name.
#' @param fn Character scalar, function name (any case).
#' @return One of "legacy", "xlfn", or "xlws".
#' @keywords internal
.prefix_for <- function(fn) {
  fn_up <- toupper(fn)
  if (fn_up %in% .spaghetti_env$XLWS)   return("xlws")
  if (fn_up %in% .spaghetti_env$XLFN)   return("xlfn")
  if (fn_up %in% .spaghetti_env$LEGACY)  return("legacy")
  return("xlfn")   # unknown: conservative default
}

#' Strip any OOXML namespace prefix from a function name.
#' @param fn Character scalar.
#' @return Clean name without _xlfn., _xlfn._xlws., or _xlpm. prefix.
#' @keywords internal
.strip_prefix <- function(fn) {
  fn <- sub("^_xlfn\\._xlws\\.", "", fn)
  fn <- sub("^_xlfn\\.",         "", fn)
  fn <- sub("^_xlpm\\.",         "", fn)
  fn
}
