# R/registry.R
#
# Source of truth: [MS-XLSX] §2.2.2 ABNF grammar, "function-list" and
# "future-function-list" productions.
# https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xlsx
#
# Four tiers:
#   LEGACY_WORKSHEET -> no prefix (modern worksheet functions, ECMA-376 §18.17)
#   LEGACY_XLM       -> no prefix (Excel 4 macro language, pre-ECMA leftovers)
#   XLFN             -> _xlfn.      (future-function-list)
#   XLWS             -> _xlfn._xlws. (FILTER, SORT — worksheet-scope dyn arrays)
#
# Worksheet vs XLM matters for .spell_suggest: typos in a .xlsx context
# should suggest worksheet functions, not XLM macro names. Both tiers
# resolve to the same "no prefix" rule in .prefix_for().
#
# ANCHORARRAY / SINGLE are synthetic wrappers generated by the translator,
# not user-facing functions, but live in XLWS so they round-trip correctly.
#
# LAMBDA parameters get _xlpm. — handled by the parser, not here.

# ---------------------------------------------------------------------------
# LEGACY_WORKSHEET — modern worksheet functions, no prefix
# ---------------------------------------------------------------------------
.spaghetti_env$LEGACY_WORKSHEET <- c(
  "ABS","ACCRINT","ACCRINTM","ACOS","ACOSH",
  "ADDRESS","AMORDEGRC","AMORLINC","AND","AREAS","ASC","ASIN","ASINH",
  "ATAN","ATAN2","ATANH","AVEDEV","AVERAGE","AVERAGEA","AVERAGEIF","AVERAGEIFS",
  "BAHTTEXT","BESSELI","BESSELJ","BESSELK","BESSELY","BETADIST","BETAINV",
  "BIN2DEC","BIN2HEX","BIN2OCT","BINOMDIST",
  "CEILING","CELL","CHAR",
  "CHIDIST","CHIINV","CHITEST","CHOOSE","CLEAN","CODE","COLUMN","COLUMNS",
  "COMBIN","COMPLEX","CONCAT","CONCATENATE","CONFIDENCE","CONVERT","CORREL",
  "COS","COSH","COUNT","COUNTA","COUNTBLANK","COUNTIF","COUNTIFS",
  "COUPDAYBS","COUPDAYS","COUPDAYSNC","COUPNCD","COUPNUM","COUPPCD","COVAR",
  "CRITBINOM",
  "CUBEKPIMEMBER","CUBEMEMBER","CUBEMEMBERPROPERTY","CUBERANKEDMEMBER",
  "CUBESET","CUBESETCOUNT","CUBEVALUE","CUMIPMT","CUMPRINC",
  "DATE","DATEDIF","DATESTRING","DATEVALUE","DAVERAGE","DAY","DAYS360",
  "DB","DBCS","DCOUNT","DCOUNTA","DDB","DEC2BIN","DEC2HEX","DEC2OCT",
  "DEGREES","DELTA","DEVSQ","DGET","DISC",
  "DMAX","DMIN","DOLLAR","DOLLARDE","DOLLARFR",
  "DPRODUCT","DSTDEV","DSTDEVP","DSUM","DURATION","DVAR","DVARP",
  "EDATE","EFFECT","EOMONTH","ERF","ERFC","ERROR.TYPE",
  "EVEN","EXACT","EXP","EXPONDIST",
  "FACT","FACTDOUBLE","FALSE","FDIST","FIND","FINDB",
  "FINV","FISHER","FISHERINV","FIXED","FLOOR",
  "FORECAST","FREQUENCY","FTEST","FV","FVSCHEDULE",
  "GAMMADIST","GAMMAINV","GAMMALN","GCD","GEOMEAN","GESTEP",
  "GETPIVOTDATA","GROWTH",
  "HARMEAN","HEX2BIN","HEX2DEC","HEX2OCT","HLOOKUP","HOUR",
  "HYPERLINK","HYPGEOMDIST",
  "IF","IFS","IFERROR","IMABS","IMAGINARY","IMARGUMENT","IMCONJUGATE",
  "IMCOS","IMDIV","IMEXP","IMLN","IMLOG10","IMLOG2","IMPOWER","IMPRODUCT",
  "IMREAL","IMSIN","IMSQRT","IMSUB","IMSUM","INDEX","INDIRECT","INFO",
  "INT","INTERCEPT","INTRATE","IPMT","IRR",
  "ISBLANK","ISERR","ISERROR","ISEVEN","ISLOGICAL","ISNA","ISNONTEXT",
  "ISNUMBER","ISODD","ISPMT","ISREF","ISTEXT","ISTHAIDIGIT",
  "KURT","LARGE","LCM","LEFT","LEFTB","LEN","LENB","LINEST",
  "LN","LOG","LOG10","LOGEST","LOGINV","LOGNORMDIST","LOOKUP","LOWER",
  "MATCH","MAX","MAXA","MAXIFS","MDETERM","MDURATION","MEDIAN","MID","MIDB",
  "MIN","MINA","MINIFS","MINUTE","MINVERSE","MIRR","MMULT","MOD","MODE",
  "MONTH","MROUND","MULTINOMIAL",
  "N","NA","NEGBINOMDIST","NETWORKDAYS","NOMINAL",
  "NORMDIST","NORMINV","NORMSDIST","NORMSINV","NOT","NOW","NPER","NPV",
  "NUMBERSTRING",
  "OCT2BIN","OCT2DEC","OCT2HEX","ODD","ODDFPRICE","ODDFYIELD","ODDLPRICE",
  "ODDLYIELD","OFFSET","OR",
  "PEARSON","PERCENTILE","PERCENTRANK","PERMUT","PHONETIC","PI",
  "PMT","POISSON","POWER","PPMT","PRICE","PRICEDISC",
  "PRICEMAT","PROB","PRODUCT","PROPER","PV",
  "QUARTILE","QUOTIENT",
  "RADIANS","RAND","RANDBETWEEN","RANK","RATE","RECEIVED",
  "REPLACE","REPLACEB","REPT","RIGHT","RIGHTB","ROMAN","ROUND",
  "ROUNDBAHTDOWN","ROUNDBAHTUP","ROUNDDOWN","ROUNDUP","ROW","ROWS","RSQ","RTD",
  "SEARCH","SEARCHB","SECOND","SERIESSUM",
  "SIGN","SIN","SINH","SKEW","SLN","SLOPE","SMALL","SQRT","SQRTPI",
  "STANDARDIZE",
  "STDEV","STDEVA","STDEVP","STDEVPA","STEYX","SUBSTITUTE","SUBTOTAL",
  "SUM","SUMIF","SUMIFS","SUMPRODUCT","SUMSQ","SUMX2MY2","SUMX2PY2","SUMXMY2",
  "SWITCH","SYD",
  "T","TAN","TANH","TBILLEQ","TBILLPRICE","TBILLYIELD","TDIST",
  "TEXT",
  "THAIDAYOFWEEK","THAIDIGIT","THAIMONTHOFYEAR","THAINUMSOUND",
  "THAINUMSTRING","THAISTRINGLENGTH","THAIYEAR",
  "TIME","TIMEVALUE","TINV","TODAY","TRANSPOSE","TREND","TRIM","TRIMMEAN",
  "TRUE","TRUNC","TTEST","TYPE",
  "UPPER","USDOLLAR",
  "VALUE","VAR","VARA","VARP","VARPA","VDB","VLOOKUP",
  "WEEKDAY","WEEKNUM","WEIBULL","WORKDAY",
  "XIRR","XNPV","YEAR","YEARFRAC","YIELD","YIELDDISC","YIELDMAT","ZTEST",
  # Outside the _xlfn() alternation in spec but still legacy worksheet:
  "ECMA.CEILING","ISO.CEILING","NETWORKDAYS.INTL","WORKDAY.INTL"
)

# ---------------------------------------------------------------------------
# LEGACY_XLM — Excel 4 macro language, no prefix
# These names only appear in .xlm macro sheets and legacy named-range macro
# bindings. They are listed because [MS-XLSX] requires them in the
# function-list grammar production and they must not be prefixed.
# ---------------------------------------------------------------------------
.spaghetti_env$LEGACY_XLM <- c(
  "ABSREF","ACTIVE.CELL","ADD.BAR","ADD.COMMAND","ADD.MENU","ADD.TOOLBAR",
  "APP.TITLE","ARGUMENT",
  "BREAK",
  "CALL","CALLER","CANCEL.KEY","CHECK.COMMAND",
  "CREATE.OBJECT","CUSTOM.REPEAT","CUSTOM.UNDO",
  "DELETE.BAR","DELETE.COMMAND","DELETE.MENU","DELETE.TOOLBAR",
  "DEREF","DIALOG.BOX","DIRECTORY","DOCUMENTS",
  "ECHO","ELSE","ELSE.IF","ENABLE.COMMAND","ENABLE.TOOL","END.IF",
  "ERROR","EVALUATE","EXEC","EXECUTE",
  "FCLOSE","FILES","FOPEN","FOR","FOR.CELL","FORMULA.CONVERT",
  "FPOS","FREAD","FREADLN","FSIZE","FWRITE","FWRITELN",
  "GET.BAR","GET.CELL","GET.CHART.ITEM","GET.DEF","GET.DOCUMENT",
  "GET.FIELD","GET.FORMULA","GET.ITEM","GET.LINK.INFO","GET.MOVIE",
  "GET.NAME","GET.NOTE","GET.OBJECT","GET.TOOL","GET.TOOLBAR","GET.VIEW",
  "GET.WINDOW","GET.WORKBOOK","GET.WORKSPACE","GOTO","GROUP",
  "HALT","HELP",
  "INITIATE","INPUT",
  "LAST.ERROR","LINKS",
  "MOVIE.COMMAND",
  "NAMES","NEXT","NOTE",
  "OPEN.DIALOG","OPTIONS.LISTS.GET",
  "PAUSE","POKE","PRESS.TOOL",
  "REFTEXT","REGISTER","REGISTER.ID","RELREF",
  "RENAME.COMMAND","REQUEST","RESET.TOOLBAR","RESTART","RESULT","RESUME",
  "RETURN",
  "SAVE.DIALOG","SAVE.TOOLBAR","SCENARIO.GET","SELECTION","SERIES",
  "SET.NAME","SET.VALUE","SHOW.BAR","SPELLING.CHECK","SPREADBASE.DATA.FIELD",
  "STEP",
  "TERMINATE","TEXT.BOX","TEXTREF",
  "UNREGISTER",
  "VIEW.GET","VOLATILE",
  "WHILE","WINDOW.TITLE","WINDOWS"
)

# ---------------------------------------------------------------------------
# XLWS — _xlfn._xlws. prefix
# ---------------------------------------------------------------------------
.spaghetti_env$XLWS <- c(
  "FILTER","SORT","ANCHORARRAY","SINGLE"
)

# ---------------------------------------------------------------------------
# XLFN — _xlfn. prefix
# Verbatim from [MS-XLSX] future-function-list, plus post-spec 365 additions.
# ---------------------------------------------------------------------------
.spaghetti_env$XLFN <- c(
  "ACOT","ACOTH","AGGREGATE","ARABIC","ARRAYTOTEXT",
  "BASE","BETA.DIST","BETA.INV","BINOM.DIST","BINOM.DIST.RANGE","BINOM.INV",
  "BITAND","BITLSHIFT","BITOR","BITRSHIFT","BITXOR",
  "BYCOL","BYROW",
  "CEILING.MATH","CEILING.PRECISE",
  "CHISQ.DIST","CHISQ.DIST.RT","CHISQ.INV","CHISQ.INV.RT","CHISQ.TEST",
  "CHOOSECOLS","CHOOSEROWS","COMBINA",
  "CONFIDENCE.NORM","CONFIDENCE.T",
  "COT","COTH","COVARIANCE.P","COVARIANCE.S","CSC","CSCH",
  "DAYS","DECIMAL","DROP",
  "ERF.PRECISE","ERFC.PRECISE","EXPAND","EXPON.DIST",
  "F.DIST","F.DIST.RT","F.INV","F.INV.RT","F.TEST",
  "FIELDVALUE","FILTERXML","FLOOR.MATH","FLOOR.PRECISE",
  "FORECAST.ETS","FORECAST.ETS.CONFINT","FORECAST.ETS.SEASONALITY",
  "FORECAST.ETS.STAT","FORECAST.LINEAR",
  "FORMULATEXT",
  "GAMMA","GAMMA.DIST","GAMMA.INV","GAMMALN.PRECISE","GAUSS",
  "HSTACK","HYPGEOM.DIST",
  "IFNA","IMAGE","IMCOSH","IMCOT","IMCSC","IMCSCH","IMSEC","IMSECH",
  "IMSINH","IMTAN",
  "ISFORMULA","ISOMITTED","ISOWEEKNUM",
  "LAMBDA","LET","LOGNORM.DIST","LOGNORM.INV",
  "MAKEARRAY","MAP","MODE.MULT","MODE.SNGL","MUNIT",
  "NEGBINOM.DIST","NORM.DIST","NORM.INV","NORM.S.DIST","NORM.S.INV",
  "NUMBERVALUE",
  "PDURATION","PERCENTILE.EXC","PERCENTILE.INC",
  "PERCENTRANK.EXC","PERCENTRANK.INC","PERMUTATIONA","PHI",
  "POISSON.DIST","PQSOURCE","PYTHON_STR","PYTHON_TYPE","PYTHON_TYPENAME",
  "QUARTILE.EXC","QUARTILE.INC","QUERYSTRING",
  "RANDARRAY","RANK.AVG","RANK.EQ","REDUCE","RRI",
  "SCAN","SEC","SECH","SEQUENCE","SHEET","SHEETS","SKEW.P","SORTBY",
  "STDEV.P","STDEV.S",
  "T.DIST","T.DIST.2T","T.DIST.RT","T.INV","T.INV.2T","T.TEST",
  "TAKE","TEXTAFTER","TEXTBEFORE","TEXTJOIN","TEXTSPLIT","TOCOL","TOROW",
  "UNICHAR","UNICODE","UNIQUE",
  "VALUETOTEXT","VAR.P","VAR.S","VSTACK",
  "WEBSERVICE","WEIBULL.DIST","WRAPCOLS","WRAPROWS",
  "XLOOKUP","XMATCH","XOR","Z.TEST"
)

# ---------------------------------------------------------------------------
# Lookup helpers
# ---------------------------------------------------------------------------

#' Determine the OOXML namespace tier for a function name.
#' @param fn Character scalar, function name (any case).
#' @return One of "legacy", "xlfn", or "xlws".
#' @keywords internal
.prefix_for <- function(fn) {
  fn_up <- toupper(fn)
  if (fn_up %in% .spaghetti_env$XLWS)             return("xlws")
  if (fn_up %in% .spaghetti_env$XLFN)             return("xlfn")
  if (fn_up %in% .spaghetti_env$LEGACY_WORKSHEET) return("legacy")
  if (fn_up %in% .spaghetti_env$LEGACY_XLM)       return("legacy")
  "xlfn"   # unknown: conservative default
}

#' Strip any OOXML namespace prefix from a function name.
#' @param fn Character scalar.
#' @return Clean name without _xlfn., _xlfn._xlws., or _xlpm. prefix.
#' @keywords internal
.strip_prefix <- function(fn) {
  fn <- sub("^_xlfn\\._xlws\\.", "", fn)
  fn <- sub("^_xlfn\\.",         "", fn)
  fn <- sub("^_xlpm\\.",         "", fn)
  fn
}

# ---------------------------------------------------------------------------
# Spell-check helper
# ---------------------------------------------------------------------------

#' Find the closest known function name(s) to an unknown token.
#'
#' Uses generalised edit distance (utils::adist) over the worksheet-function
#' registry (LEGACY_WORKSHEET ∪ XLFN ∪ XLWS). XLM macro names are excluded
#' from suggestions since user typos in worksheet contexts are almost
#' never typos of XLM names.
#'
#' Returns up to `n` suggestions, or character(0) if the closest match is
#' more than `max_dist` edits away.
#'
#' @param fn       Unknown function name (uppercase).
#' @param n        Maximum number of suggestions to return (default 3).
#' @param max_dist Maximum edit distance to consider a useful suggestion (default 3).
#' @return Character vector of suggestions, possibly empty.
#' @keywords internal
.spell_suggest <- function(fn, n = 3L, max_dist = 3L) {
  candidates <- c(
    .spaghetti_env$LEGACY_WORKSHEET,
    .spaghetti_env$XLFN,
    .spaghetti_env$XLWS
  )
  dists <- utils::adist(fn, candidates)[1L, ]
  ord   <- order(dists)
  keep  <- ord[seq_len(min(n, length(ord)))]
  keep  <- keep[dists[keep] <= max_dist]
  if (length(keep) == 0L) return(character(0))
  candidates[keep]
}

#' Emit a warning for an unknown function name, with spelling suggestions.
#'
#' Called from .transform_to_xml() when warn_unknown = TRUE.
#'
#' @param fn Unknown function name (uppercase).
#' @keywords internal
.warn_unknown_fn <- function(fn) {
  suggestions <- .spell_suggest(fn)
  if (length(suggestions) > 0L) {
    warning(
      "Unknown function: ", fn,
      ". Did you mean: ", paste(suggestions, collapse = ", "), "?",
      call. = FALSE
    )
  } else {
    warning(
      "Unknown function: ", fn,
      ". It will be prefixed with _xlfn. but may not be recognised.",
      call. = FALSE
    )
  }
}
