# R/zzz.R
# Package initialisation.
#
# Load order (alphabetical):
#   aaa.R       — creates .spaghetti_env
#   lexer.R
#   locales.R   — defines lookup helpers (reads .spaghetti_env$FUNCTIONS)
#   registry.R  — populates LEGACY / XLFN / XLWS
#   translate.R
#   utils.R
#   zzz.R       — .onLoad() fires last, loads the RDS into FUNCTIONS

.onLoad <- function(libname, pkgname) {

  # Load the pre-built function table from the package data directory.
  # This file is generated by data-raw/parse_locales.R from Microsoft TBX files.
  rds_path <- system.file("extdata", "excel_functions.rds", package = pkgname)

  EXCEL_FUNCTIONS <- c(.spaghetti_env$LEGACY, .spaghetti_env$XLFN, .spaghetti_env$XLWS)

  if (nzchar(rds_path) > 0 && file.exists(rds_path)) {
    .spaghetti_env$FUNCTIONS <- readRDS(rds_path)
  } else {
    # RDS not present (e.g. fresh clone before parse_locales.R has been run).
    # Initialise with an empty frame so the package still loads cleanly.
    # locale lookup functions will return their input unchanged.
    .spaghetti_env$FUNCTIONS <- data.frame(
      fn          = EXCEL_FUNCTIONS,   # from registry.R / aaa.R
      description = NA_character_,
      stringsAsFactors = FALSE
    )
    # packageStartupMessage(
    #   "spaghetti: locale data not found. ",
    #   "Run data-raw/parse_locales.R to generate data/excel_functions.rds."
    # )
  }

  invisible(NULL)
}
